Typos 🙂
romanovichim/TonFunClessons_Eng pull request #9
Opened 2022-12-08 15:14 UTC by liketurbo

2022-12-10 02:07 UTC, Timoteo714 commented
>

2022-12-10 19:46 UTC, Timoteo714 approved these changes
[](notification)

2022-12-10 21:30 UTC, Timoteo714 requested changes
Algorithms are the best .

2022-12-11 19:49 UTC, liketurbo commented
Closing cause similar one is exists 👋

2022-12-11 19:49 UTC, closed without merging